//
//  PlaylistRouter.swift
//  4champ
//
//  Created by Aleksi Sitomaniemi on 15.3.2020.
//  Copyright © 2020 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlaylistRoutingLogic {
  func toPlaylistSelector(module: MMD)
}

protocol PlaylistDataPassing
{
  var dataStore: PlaylistDataStore? { get }
  var viewController: UIViewController? { get set }
}

class PlaylistRouter: NSObject, PlaylistRoutingLogic, PlaylistDataPassing
{
//  weak var viewController: PlaylistViewController?
  var dataStore: PlaylistDataStore?
  var viewController: UIViewController?
    
  // MARK: Routing
  func toPlaylistSelector(module: MMD) {
      let hvc = PlaylistSelectorStore.buildPicker(module: module)
      viewController?.present(hvc, animated: true, completion: nil)
  }
}
