//
//  PlaylistInteractor.swift
//  4champ
//
//  Created by Aleksi Sitomaniemi on 15.3.2020.
//  Copyright © 2020 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreData

protocol PlaylistBusinessLogic {
  func addPresenter(_ presenter: PlaylistPresentationLogic)
  func removePresenter(_ presenter: PlaylistPresentationLogic)
  func selectPlaylist(request: Playlists.Select.Request)
  func removeModule(request: Playlists.Remove.Request)
  func moveModule(request: Playlists.Move.Request)
  func toggleShuffle()
  func importModules()
  func toggleFavorite(request: Playlists.Favorite.Request)
  func playModule(request: Playlists.Play.Request)
  func startPlaylist(request: Playlists.Start.Request)
}

protocol PlaylistDataStore {
  var playlists: [PLMD] { get }
  var selectedPlaylistId: String? { get }
  // var name: String { get set }
}

class PlaylistInteractor: NSObject, PlaylistBusinessLogic, PlaylistDataStore {
  
  static let sharedInstance = PlaylistInteractor()
  
  var presenters: [PlaylistPresentationLogic] = []
  var selectedPlaylistId: String?
  var frc: NSFetchedResultsController<Playlist>?
  var playlists: [PLMD] = []

  private var downloadController = DownloadController.init()

  override init() {
    super.init()
    let filterString = "plId != 'radioList'"

    let fetchRequest = NSFetchRequest<Playlist>.init(entityName: "Playlist")
    fetchRequest.sortDescriptors = []
    fetchRequest.predicate = NSPredicate.init(format: filterString)
    frc = moduleStorage.createFRC(fetchRequest: fetchRequest, entityName: "Playlist")
    frc?.delegate = self
    do {
      try frc?.performFetch()
      rebuildList()
    } catch {
      log.error("Failed to perform fetch: \(error)")
    }

    if selectedPlaylistId == nil {
      selectedPlaylistId = "default"
    }

    moduleStorage.addStorageObserver(self)

  }

  // MARK: Interactions
  func addPresenter(_ presenter: PlaylistPresentationLogic) {
    self.presenters.append(presenter)
  }
  func removePresenter(_ presenter: PlaylistPresentationLogic) {
    self.presenters.removeAll(where: { $0.presenterId == presenter.presenterId })
  }
  func selectPlaylist(request: Playlists.Select.Request) {
    if request.playlistId.count > 0 {
      selectedPlaylistId = request.playlistId
    }
    if let pl = frc?.fetchedObjects?.first(where: { ($0 as Playlist).plId == selectedPlaylistId }) {
      let resp = Playlists.Select.Response(selectedPlaylist: pl)
      settings.lastActivePlaylist = pl.plId ?? "default"
      presenters.forEach { $0.presentPlaylist(response: resp) }
    } else {
      if selectedPlaylistId != "default" {
        // playlist not found => go to default
        selectPlaylist(request: Playlists.Select.Request(playlistId: "default"))
      }
    }
  }

  func removeModule(request: Playlists.Remove.Request) {
    if let pl = frc?.fetchedObjects?.first(where: { ($0 as Playlist).plId == selectedPlaylistId }) {
      pl.removeFromModules(at: request.modIndex)
      moduleStorage.saveContext()
      let resp = Playlists.Select.Response(selectedPlaylist: pl)
      presenters.forEach { $0.presentPlaylist(response: resp) }
    }
  }

  func moveModule(request: Playlists.Move.Request) {
    if let pl = frc?.fetchedObjects?.first(where: { ($0 as Playlist).plId == selectedPlaylistId }) {

      let modSet = pl.modules?.mutableCopy() as? NSMutableOrderedSet

      var targetIndex = request.newIndex
      if targetIndex > request.modIndex {
        targetIndex -= 1
      }

      modSet?.moveObjects(at: IndexSet.init([request.modIndex]), to: targetIndex)
      pl.modules = modSet
      moduleStorage.saveContext()
      let resp = Playlists.Select.Response(selectedPlaylist: pl)
      presenters.forEach { $0.presentPlaylist(response: resp) }
    }
  }

  func toggleShuffle() {
    var currentMode: Bool = moduleStorage.currentPlaylist?.playmode?.boolValue ?? false
    currentMode.toggle()
    moduleStorage.currentPlaylist?.playmode = NSNumber.init(value: currentMode)
    moduleStorage.saveContext()
    rebuildQueue()
  }

  func toggleFavorite(request: Playlists.Favorite.Request) {
    if let mod = moduleStorage.getModuleById(request.modId) {
      _ = moduleStorage.toggleFavorite(module: mod)
    }
    doPresentMetadataChanged()
  }

  func playModule(request: Playlists.Play.Request) {
    rebuildQueue()
    if let index = modulePlayer.playQueue.index(of: request.mmd) {
      modulePlayer.play(at: index)
    }
  }

  func startPlaylist(request: Playlists.Start.Request) {
    rebuildQueue()
    if request.shuffleMode != .userPreference {
      let shuffle = request.shuffleMode == .shuffle
      moduleStorage.currentPlaylist?.playmode = NSNumber.init(value: shuffle)
      moduleStorage.saveContext() // will call rebuildqueue on change
    }
    modulePlayer.play(at: 0)
  }

  func importModules() {
    downloadController.rootViewController = ShareUtility.topMostController()
    downloadController.selectImportModules(addToPlaylist: true)
  }

  private func rebuildQueue() {
    if let pl = frc?.fetchedObjects?.first(where: { ($0 as Playlist).plId == selectedPlaylistId }) {
      var playlistQueue: [MMD] = []
      pl.modules?.forEach {
        if let modInfo = $0 as? ModuleInfo {
          playlistQueue.append(MMD(cdi: modInfo))
        }
      }

      if pl.playmode?.boolValue ?? false {
        playlistQueue.shuffle()
      }

      moduleStorage.currentPlaylist = pl
      modulePlayer.setNewPlayQueue(queue: playlistQueue, queueName: pl.getDisplayName())
    }
  }
  
  private func rebuildList() {
    let plObjects = frc?.fetchedObjects ?? []
    
    var plMetaData = plObjects.map {
      var meta = PLMD(id: $0.plId, name: $0.plName, current: false, modules: [] )
      $0.modules?.forEach { modInfo in
        if let mi = modInfo as? ModuleInfo {
          meta.modules.append(MMD(cdi: mi))
        }
      }
      return meta
    }
            
    plMetaData.sort { (pla, plb) -> Bool in
      if pla.id == "default" {
        return true
      }
      if plb.id == "default" {
        return false
      }
      return pla.name! < plb.name!
    }
    
    playlists = plMetaData
  }

  private func doPresentMetadataChanged() {
    if let pl = frc?.fetchedObjects?.first(where: { ($0 as Playlist).plId == selectedPlaylistId }) {
      let resp = Playlists.Select.Response(selectedPlaylist: pl)
      presenters.forEach { $0.presentMetadataChanged(response: resp) }
    }
  }
}

extension PlaylistInteractor: NSFetchedResultsControllerDelegate {
  func controllerWillChangeContent(_ controller: NSFetchedResultsController<NSFetchRequestResult>) {
  }

  func controller(_ controller: NSFetchedResultsController<NSFetchRequestResult>,
                  didChange anObject: Any,
                  at indexPath: IndexPath?,
                  for type: NSFetchedResultsChangeType,
                  newIndexPath: IndexPath?) {

    guard modulePlayer.radioOn == false else {
      return
    }

    if let pl = anObject as? Playlist, pl.plId == selectedPlaylistId {
      rebuildQueue()
    } else {
      rebuildList()
    }
  }

  func controllerDidChangeContent(_ controller: NSFetchedResultsController<NSFetchRequestResult>) {
    doPresentMetadataChanged()
  }
}

extension PlaylistInteractor: ModuleStorageObserver {
  func metadataChange(_ mmd: MMD) {
    doPresentMetadataChanged()
  }

  func playlistChange() {
  }
}
