//
//  PlaylistModels.swift
//  4champ
//
//  Created by Aleksi Sitomaniemi on 15.3.2020.
//  Copyright © 2020 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Playlists {
  // MARK: Use cases

    enum Favorite {
        struct Request {
            let modId: Int
        }
        struct Response {
        }
        struct ViewModel {
        }
    }

    enum Play {
        struct Request {
            let mmd: MMD
        }
    }

    enum Select {
        struct Request {
            let playlistId: String
        }
        struct Response {
            let selectedPlaylist: Playlist
        }
        struct ViewModel {
            var playlistName: String
            var shuffle: Bool
            var modules: [MMD]
        }
    }

    enum Remove {
        struct Request {
            let modIndex: Int
        }
    }

    enum Move {
        struct Request {
            let modIndex: Int
            let newIndex: Int
        }
        struct Response {
            let modIndex: Int
            let newIndex: Int
        }
        struct ViewModel {
            let modIndex: Int
            let newIndex: Int
        }
    }

}
