//
//  AboutRouter.swift
//  4champ
//
//  Created by Aleksi Sitomaniemi on 12/06/2018.
//  Copyright (c) 2018 boogie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol AboutRoutingLogic
{
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol AboutDataPassing
{
  var dataStore: AboutDataStore? { get }
}

class AboutRouter: NSObject, AboutRoutingLogic, AboutDataPassing
{
  weak var viewController: AboutViewController?
  var dataStore: AboutDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: AboutViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: AboutDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
