//
//  AboutModels.swift
//  4champ
//
//  Created by Aleksi Sitomaniemi on 12/06/2018.
//  Copyright (c) 2018 boogie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum About
{
  struct Details {
    var titles:[String]
    var contents:[String]
    var images:[String]
    var licenseLinks:[String]
    var licenseNames:[String]
  }
  // MARK: Use cases
  
  enum Status
  {
    struct Request
    {
    }
    struct Response
    {
      var isPlaying: Bool = false
    }
    struct ViewModel
    {
      var isPlaying: Bool = false
    }
  }
}
