//
//  AboutWorker.swift
//  4champ
//
//  Created by Aleksi Sitomaniemi on 12/06/2018.
//  Copyright (c) 2018 Aleksi Sitomaniemi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AboutWorker
{
  func doSomeWork()
  {
  }
}
