//
//  AboutInteractor.swift
//  4champ
//
//  Created by Aleksi Sitomaniemi on 12/06/2018.
//  Copyright (c) 2018 boogie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AboutBusinessLogic
{
  var details: About.Details { get }
}

protocol AboutDataStore
{
  var details: About.Details { get }
}

class AboutInteractor: AboutBusinessLogic, AboutDataStore
{
  var presenter: AboutPresentationLogic?
  
  var details: About.Details
  
  init() {
    let aboutTitle: String
    if let ver = Bundle.main.object(forInfoDictionaryKey: "CFBundleVersion") as? String,
      let build = Bundle.main.object(forInfoDictionaryKey: "CWBuildNumber") as? String {
      aboutTitle = "4champ \(ver) (\(build))"
    } else {
      aboutTitle = "0.0"
    }
    let titleKeys = [aboutTitle, "Twitter","About_Copyrights", /*"TabBar_Local", "TabBar_Search", "TabBar_Playlist",*/ "TabBar_Radio", "About_Licenses"]
    let contentKeys = ["AboutView_Info", "AboutView_Twitter", "AboutView_Legal", /*"AboutView_Local", "AboutView_Search", "AboutView_Playlists",*/ "AboutView_Radio"]
    let imageKeys = ["about", "twitter_small", "legal", /*"localMods", "search", "playlist", */ "radio", "about"]
    let lics = ["Alamofire", "HivelyTracker", "InAppSettingsKit", "KVNProgress", "LibOpenMPT"]
    let licUrls = ["https://github.com/Alamofire/Alamofire/blob/master/LICENSE",
                   "HivelyTracker replayer source code is public domain, see http://www.hivelytracker.co.uk/forum.php?action=viewthread&id=114",
                   "https://github.com/futuretap/InAppSettingsKit/blob/master/LICENSE",
                   "https://github.com/AssistoLab/KVNProgress/blob/master/LICENSE",
                   "https://lib.openmpt.org/libopenmpt/#sec_license"]
    
    details = About.Details(titles: titleKeys, contents: contentKeys, images: imageKeys, licenseLinks: licUrls, licenseNames: lics)
  }
}
