//
//  PlaylistSelectorModels.swift
//  4champ
//
//  Created by Aleksi Sitomaniemi on 13.3.2020.
//  Copyright (c) 2020 boogie. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct PLMD: Identifiable {
    var id: String?
    var name: String?
    var current: Bool
    var modules: [Int]
}

enum PlaylistSelector
{
  enum PrepareSelection
  {
    struct Request
    {
        let module: MMD
    }
    struct Response
    {
        let module: MMD
        let playlistOptions: [PLMD]
    }
    struct ViewModel
    {
        var module: String
        var playlistOptions: [String]
        var progress: Float = 1
        var success: Bool = true
    }
  }
    
    enum Append {
        struct Request {
            let module: MMD
            let playlistIndex: Int
        }
        struct Response {
            let progress: Float
            var error: Error?
        }
        struct ViewModel {
            let progress: Float
            let success: Bool
        }
    }
}
